import { GateError, buildRelease, fixture, hostInstructions, makeCandidate, prepare, reviewInstructions, status, validateCouncil } from '../../lib/maestro.js';

export const config={api:{bodyParser:false,responseLimit:false},maxDuration:300};
const MAX=400000;
const key=()=>String(process.env.OPENAI_API_KEY||process.env.OPEN_AI_KEY||process.env.OPENAI_KEY||'').trim();
function secure(res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY')}
async function body(req){const chunks=[];let n=0;for await(const chunk of req){n+=chunk.length;if(n>MAX)throw new GateError('BODY_TOO_LARGE','Request body exceeds 400 KB.',413);chunks.push(chunk)}if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw new GateError('INVALID_JSON','Request body must be valid JSON.',422)}}
function enforce(req){if(req.headers['x-maestro-request']!=='1')throw new GateError('REQUEST_HEADER','Missing Maestro request header.',403);const origin=req.headers.origin;if(origin){const host=String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim();let oh='';try{oh=new URL(origin).host}catch{}if(!host||oh!==host)throw new GateError('ORIGIN','Cross-origin API requests are blocked.',403)}}
function inputs(d){if(!d.request||!d.plan||!d.cues)throw new GateError('MISSING_INPUT','Provide request, plan, and cues.');return[d.request,d.plan,d.cues]}
async function aiJson(model,system,user){const token=key();if(token.length<16)throw new GateError('AI_KEY_REQUIRED','The Vercel project does not have a usable server-side OpenAI key configured.',422);if(typeof model!=='string'||!/^[A-Za-z0-9._:/-]{1,100}$/.test(model))throw new GateError('AI_MODEL','Enter a valid model ID.');const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'user',content:user}],response_format:{type:'json_object'},max_completion_tokens:10000})});if(!r.ok)throw new GateError('AI_PROVIDER',`OpenAI returned HTTP ${r.status}. No credential or provider body was stored.`,502);const j=await r.json();try{return JSON.parse(j.choices[0].message.content)}catch{throw new GateError('AI_JSON','The provider returned invalid JSON.',502)}}
export default async function handler(req,res){secure(res);const path=Array.isArray(req.query.path)?req.query.path.join('/'):String(req.query.path||'');try{
 if(req.method==='GET'&&path==='status'){const s=status();s.ai={provider:'OpenAI',server_key_configured:Boolean(key()),credential_delivery:'server_env_only'};return res.status(200).json(s)}
 if(req.method==='GET'&&path==='fixture')return res.status(200).json(fixture());
 if(req.method!=='POST')return res.status(405).json({status:'BLOCKED',gate:'METHOD',message:'Method not allowed.'});enforce(req);const d=await body(req);
 if(path==='prepare')return res.status(200).json(prepare(d.request));
 if(path==='candidate'){const[a,b,c]=inputs(d);return res.status(200).json(makeCandidate(a,b,c))}
 if(path==='review-check'){const[a,b,c]=inputs(d);return res.status(200).json(validateCouncil(d.review,makeCandidate(a,b,c)))}
 if(path==='release'){const[a,b,c]=inputs(d),o=buildRelease(a,b,c,d.review);res.setHeader('Content-Type','application/zip');res.setHeader('Content-Disposition','attachment; filename="maestro-validated-prompts.zip"');res.setHeader('X-Maestro-Scope','PROMPT_ONLY');res.setHeader('X-Maestro-Digest',o.candidate.candidate_digest);return res.status(200).send(o.archive)}
 if(path==='ai/plan'){if(!d.request)throw new GateError('MISSING_INPUT','Provide a request object.');const r=await aiJson(d.model||'gpt-4.1',hostInstructions(d.request),JSON.stringify(d.request));if(!r?.plan||!r?.cues)throw new GateError('AI_PLAN_SHAPE','The AI must return plan and cues objects.');r.plan.source_digest=prepare(d.request).source_digest;const candidate=makeCandidate(d.request,r.plan,r.cues);return res.status(200).json({plan:r.plan,cues:r.cues,candidate,status:'CANDIDATE_VALIDATED',provider_calls:1})}
 if(path==='ai/review'){const[a,b,c]=inputs(d),candidate=makeCandidate(a,b,c),review=await aiJson(d.model||'gpt-4.1',reviewInstructions(candidate),JSON.stringify({request:a,plan:b,cues:c,candidate}));return res.status(200).json({review,validation:validateCouncil(review,candidate),status:'REVIEW_VALIDATED'})}
 return res.status(404).json({status:'BLOCKED',gate:'NOT_FOUND',message:'API route not found.'});
}catch(e){if(e instanceof GateError)return res.status(e.status||422).json(e.asObject());console.error('maestro_api_error',e?.name||'Error');return res.status(500).json({status:'BLOCKED',gate:'SERVER',message:'Unexpected server error. Nothing was released.'})}}
