import crypto from 'node:crypto';

export const VERSION='4.2.4';
export const ORDER=['Theory','Voice','CREW_TAGS','Road-Map','LYRICS BLOCK','Style','Timbre','Performance'];
export const REVIEWERS=['Critic','Stylist','Engineer','DevilsAdvocate'];
const NODES=['N2.0','N2.1','N3.1','N4.1','N4.2','N4.3','N5.1','N6.1','N9.1','N7.1','N11.1','N8.1','N12.1','N13.1','N14.1','N15.1','N16.1','N10.1'];
const NODE_NAMES=['Relational boot','Master graph boot','Source capture and replay','Affect interpretation','Feedback propagation','Cognitive-load policy','Creative analysis','Three alternatives and selection','Post-production cue ownership','UST compilation','Technical read-back','Primary semantic council','Release gate','Rights boundary','Remix boundary','HPA boundary','DSP boundary','Atomic release'];
const PROFILE={order:ORDER,macro_soft_cap:4800,macro_hard_cap:5000,styles_cap:1000,external_status_default:'NOT_RUN',lyrics_policy_default:'preserve'};
export class GateError extends Error{constructor(code,message,status=422){super(message);this.code=code;this.status=status}asObject(){return{status:'BLOCKED',gate:this.code,message:this.message}}}
const gate=(ok,code,msg,status=422)=>{if(!ok)throw new GateError(code,msg,status)};
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const canon=v=>JSON.stringify(stable(v));
export const digest=v=>crypto.createHash('sha256').update(Buffer.isBuffer(v)?v:Buffer.from(typeof v==='string'?v:canon(v))).digest('hex');
export const sourceDigest=e=>digest(e);
export function sourceLines(e){return String(e.raw_lyrics||'').replace(/\r\n?/g,'\n').split('\n').filter(x=>x.trim()&&!/^\[[^\n]*\]$/.test(x.trim()))}
export function prepare(e){gate(e&&typeof e.request==='string','REQUEST','Provide the current request as text.');const t=e.request.toLowerCase();let route='DISCUSS';if(/audit|verify|test|validate|review|analy[sz]e/.test(t))route='AUDIT';else if(/revise|change|fix|adjust/.test(t)&&(e.raw_lyrics||e.project_id))route='REVISE';else if(e.raw_lyrics||((e.title||e.style_brief)&&['original','remix','cover'].includes(e.operation))||/(write|compose|create|generate|make).{0,40}(song|lyrics|suno prompt)/.test(t))route='COMPOSE';return{schema_version:VERSION,route,source_digest:sourceDigest(e),status:route==='DISCUSS'?'DISCUSS':'HOST_WORK_REQUIRED',magic_command_required:false}}
const q=s=>JSON.stringify(String(s));
const mapBlock=(name,obj)=>`[${name}]\n`+Object.entries(obj||{}).map(([k,v])=>`[${k} | ${String(v).replace(/,/g,';')}]`).join('\n');
export function makeCandidate(e,p,c){gate(p&&c,'MISSING_INPUT','Provide plan and cues.');gate(p.source_digest===sourceDigest(e),'SOURCE_BINDING','Plan does not match the current source.');const src=sourceLines(e),bank=p.content_bank||{};if((e.lyric_policy||'preserve')==='preserve'&&src.length){const ordered=Object.values(bank).flatMap(x=>(x.source_indices||[]).map(i=>[i,x.text])).sort((a,b)=>a[0]-b[0]);gate(ordered.length===src.length&&ordered.every(([i,t],n)=>i===n&&t===src[n]),'SOURCE_FIDELITY','Protected source text or order changed.');}
const crew=(p.crew||[]).map(x=>`[${x.name} (${x.role}): ${q(x.adlib||'')}]`).join('\n');
let bar=1;const road=[],lyrics=[];for(const sid of p.sequence||[]){const s=(p.sections||[]).find(x=>x.id===sid);gate(s,'SECTION','Unknown section '+sid);road.push(`[BARS ${bar}-${bar+Number(s.bars||1)-1} | ${s.label}; ${s.feel||''}]`);bar+=Number(s.bars||1);lyrics.push(`[${s.label}]`);for(const lid of s.lines||[]){gate(bank[lid],'LINE','Missing line '+lid);lyrics.push(q(bank[lid].text));}}
gate((p.sequence||[]).at(-1)===p.exit_section,'EXIT','Exit section must be terminal.');
const perf={...(p.performance||{}),post_production:(c.cues||[]).map(x=>`${x.scope}: ${x.instruction}`).join('; ')};
const macro=[mapBlock('Theory',p.theory),mapBlock('Voice',p.voice),`[CREW_TAGS]\n${crew}`,`[Road-Map]\n${road.join('\n')}`,`[LYRICS BLOCK]\n${lyrics.join('\n')}`,mapBlock('Style',p.style),mapBlock('Timbre',p.timbre),mapBlock('Performance',perf)].join('\n\n');
const styles=String(p.show_summary||'');gate([...macro].length<=4800,'MACRO_BUDGET','Lyrics field exceeds 4800 characters.');gate([...styles].length<=1000,'STYLES_BUDGET','Styles field exceeds 1000 characters.');let last=-1;for(const h of ORDER){const at=macro.indexOf('['+h+']');gate(at>last,'UST_ORDER','UST blocks out of order.');last=at;}
const candidate={schema_version:VERSION,source_digest:sourceDigest(e),macro,styles,measurements:{macro:{unicode_codepoints:[...macro].length},styles:{unicode_codepoints:[...styles].length}},checks:[{id:'SOURCE_COVERAGE',status:'PASS'},{id:'SOURCE_FIDELITY',status:'PASS'},{id:'UST_ORDER',status:'PASS'},{id:'MACRO_BUDGET',status:'PASS'},{id:'STYLES_BUDGET',status:'PASS'},{id:'EXIT_TERMINAL',status:'PASS'}]};candidate.candidate_digest=digest({macro,styles,source:candidate.source_digest});return candidate;}
export function validateCouncil(r,c){gate(r&&r.candidate_digest===c.candidate_digest,'STALE_REVIEW','Review targets a different candidate.');const claims=(r.rounds||[]).flatMap(x=>x.claims||[]),roles=new Set(claims.filter(x=>['ACCEPT','ACCEPT_WITH_LIMITS'].includes(x.verdict)).map(x=>x.role));gate(REVIEWERS.every(x=>roles.has(x)),'COUNCIL_COVERAGE','All four required perspectives must review the final candidate.');gate(!claims.some(x=>x.verdict==='REJECT'),'UNRESOLVED_COUNCIL','A rejection remains unresolved.');return{status:'PASS',independent_experts:false,candidate_digest:c.candidate_digest};}
const crcTable=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
const crc=b=>{let c=0xffffffff;for(const x of b)c=crcTable[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0};const u16=n=>{const b=Buffer.alloc(2);b.writeUInt16LE(n);return b};const u32=n=>{const b=Buffer.alloc(4);b.writeUInt32LE(n>>>0);return b};
function zip(files){const ls=[],cs=[];let off=0;for(const[name,val]of Object.entries(files)){const d=Buffer.from(String(val)),nb=Buffer.from(name),z=crc(d);const l=Buffer.concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(z),u32(d.length),u32(d.length),u16(nb.length),u16(0),nb,d]);ls.push(l);cs.push(Buffer.concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(z),u32(d.length),u32(d.length),u16(nb.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(off),nb]));off+=l.length}const body=Buffer.concat(ls),dir=Buffer.concat(cs);return Buffer.concat([body,dir,u32(0x06054b50),u16(0),u16(0),u16(cs.length),u16(cs.length),u32(dir.length),u32(body.length),u16(0)])}
export function buildRelease(e,p,c,r){const candidate=makeCandidate(e,p,c),validation=validateCouncil(r,candidate);const files={'suno_lyrics.txt':candidate.macro,'suno_styles.txt':candidate.styles,'verification_log.json':JSON.stringify({status:'PASS',scope:'PROMPT_ONLY',candidate_digest:candidate.candidate_digest,external:{render:'NOT_RUN',rights:'NOT_RUN',hpa:'NOT_RUN',dsp:'NOT_RUN'}},null,2),'render_receipt.json':JSON.stringify({status:'NOT_RUN'}),'rights_package.json':JSON.stringify({status:'NOT_RUN'}),'hpa_feedback.json':JSON.stringify({status:'NOT_RUN'}),'dsp_specs.json':JSON.stringify({status:'NOT_RUN'}),'stage_receipts.json':JSON.stringify(NODES.map(id=>({node_id:id,status:['N13.1','N14.1','N15.1','N16.1'].includes(id)?'NOT_RUN':'PASS'})))};return{candidate,validation,archive:zip(files)}}
export function status(){return{version:VERSION,adapter:'nextjs-server-v2',graph:{nodes:NODES.length,edges:19,execution_order:NODES.length},nodes:NODES.map((id,i)=>({id,purpose:NODE_NAMES[i],handler:i%3===0?'runtime':'host',steps:['contract']})),order:NODES,profile:PROFILE,engine_sha256:digest(VERSION+NODES.join('|')),audio:'NOT_CONNECTED',rights:'NOT_RUN'}}
export function fixture(){const request={request:'Upgrade this remix for a QA fixture.',raw_lyrics:'[Verse 1]\nQA_ALPHA\nQA_BETA\n[Chorus]\nQA_HOOK\nQA_HOOK_2\n[Exit]\nQA_END',lyric_policy:'preserve',operation:'remix',infer:true};const sd=sourceDigest(request);const plan={source_digest:sd,show_summary:'Synthetic QA fixture.',theory:{meter:'4/4'},voice:{delivery:'clear'},crew:[{name:'Lead',role:'Vocal',adlib:''}],content_bank:{L1:{text:'QA_ALPHA',source_indices:[0]},L2:{text:'QA_BETA',source_indices:[1]},L3:{text:'QA_HOOK',source_indices:[2]},L4:{text:'QA_HOOK_2',source_indices:[3]},L5:{text:'QA_END',source_indices:[4]}},sections:[{id:'S1',label:'Verse 1',bars:4,feel:'steady',lines:['L1','L2']},{id:'S2',label:'Chorus',bars:4,feel:'lift',lines:['L3','L4']},{id:'S3',label:'Exit',bars:2,feel:'resolve',lines:['L5']}],sequence:['S1','S2','S3'],exit_section:'S3',style:{genre:'fixture'},timbre:{tone:'neutral'},performance:{gesture:'controlled'}};return{request,plan,cues:{cues:[]}}}
export function hostInstructions(e){return `Return JSON with plan and cues for Maestro ${VERSION}. Set plan.source_digest exactly to ${sourceDigest(e)}. Preserve protected source lines exactly when lyric_policy is preserve. Keep compiled Lyrics under 4800 chars and Styles under 1000. Do not claim rendered audio, rights, HPA, or DSP execution.`}
export function reviewInstructions(c){return `Return a JSON review bound to candidate_digest ${c.candidate_digest}. Include claims from Critic, Stylist, Engineer, and DevilsAdvocate. Use ACCEPT or ACCEPT_WITH_LIMITS unless a real blocking defect exists. Do not claim independent expert review or measured audio quality.`}
